spring.application.name=realTimeChat

# h2 DB
spring.datasource.url = jdbc:h2:mem:helpdesk;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
## JPA Lazy Loading
spring.jpa.open-in-view=false

# h2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace

# Jackson
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
