# dataSource
spring.datasource.url=jdbc:mysql://localhost:3306/dev
spring.datasource.username=ejDev
spring.datasource.password=0000
spring.datasource.driver-class-name=com.eojin

# JPA
## ?? ???? ??? ?? -> ?? ??? ????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
## JPA Lazy Loading
spring.jpa.open-in-view=false